export const BRAND = {
  name: 'PlanetFashion',
  tagline: 'Wear Your Planet — Minimal • Modern • Timeless',
  description: 'PlanetFashion — Curated LifeWear for Women, Men, Kids & Baby. Slow fashion, planet-friendly essentials.',
  companyLegal: 'PlanetFashion Pvt Ltd',
  supportEmail: 'hello@planetfashion.com',
  supportPhone: '+43 1 234 5678',
  address: 'Mariahilfer Straße 50, 1070 Vienna, Austria',
  currency: 'EUR',
  currencySymbol: '€',
  locale: 'en-AT',
  colors: {
    primary: '#e10600',
    primaryDark: '#b80500',
    secondary: '#0a0a0a',
    accent: '#e10600',
    accentDark: '#b80500',
    background: '#ffffff',
    surface: '#ffffff',
    text: '#0a0a0a',
    muted: '#6b7280',
    border: '#e5e7eb',
    success: '#16a34a',
    warning: '#f59e0b',
    error: '#e10600',
    special: '#e10600',
    halfPrice: '#be123c',
  },
  fonts: {
    heading: '"Space Grotesk", "Helvetica Neue", Arial, sans-serif',
    body: '"Inter", "Helvetica Neue", Arial, sans-serif',
  },
  logo: '/planetfashion-logo.svg',
  favicon: '/favicon.ico',
  social: {
    instagram: 'https://instagram.com/planetfashion',
    facebook: 'https://facebook.com/planetfashion',
  },
} as const;
