import type { Course, Package, Quiz, LiveClass, PdfResource } from './types';

export const DEMO_PDFS: PdfResource[] = [
  { id:'pdf1', title:'UPSC Syllabus 2026 - Prelims & Mains', url:'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', pages: 42, sizeKB: 1240, uploadedAt: Date.now() },
  { id:'pdf2', title:'NCERT Summary - History - Ancient India', url:'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', pages: 88, sizeKB: 2100, uploadedAt: Date.now() },
  { id:'pdf3', title:'Daily Current Affairs - 02 Sep 2026', url:'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', pages: 12, sizeKB: 560, uploadedAt: Date.now() },
  { id:'pdf4', title:'Indian Polity Notes - Laxmikant Ch 1-5', url:'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', pages: 64, sizeKB: 1800, uploadedAt: Date.now() },
];

export const DEMO_QUIZZES: Quiz[] = [
  {
    id:'quiz-polity-1',
    title:'Indian Polity - Mock Test 1',
    description:'50 MCQs • Polity basics, Constitution, Parliament',
    totalMarks: 100,
    durationMin: 60,
    passPercent: 33,
    isPublished: true,
    createdAt: Date.now(),
    questions: [
      { id:'q1', type:'single', question:'Which article of the Constitution deals with the Right to Equality?', options:['Article 14','Article 19','Article 21','Article 32'], correctIndices:[0], explanation:'Article 14 guarantees equality before law.', marks:2 },
      { id:'q2', type:'single', question:'The concept of Directive Principles is borrowed from which country?', options:['USA','Ireland','Australia','Canada'], correctIndices:[1], marks:2 },
      { id:'q3', type:'single', question:'Who is the guardian of the Constitution?', options:['President','Parliament','Supreme Court','Prime Minister'], correctIndices:[2], marks:2 },
      { id:'q4', type:'multiple', question:'Which of the following are Fundamental Rights?', options:['Right to Equality','Right to Property','Right to Freedom','Right to Constitutional Remedies'], correctIndices:[0,2,3], marks:2 },
    ]
  },
  {
    id:'quiz-csat-1',
    title:'CSAT - Comprehension & Reasoning',
    description:'30 MCQs • CSAT Paper II practice',
    totalMarks: 60,
    durationMin: 45,
    passPercent: 33,
    isPublished: true,
    createdAt: Date.now(),
    questions: [
      { id:'q1', type:'single', question:'If all roses are flowers and some flowers fade quickly, which follows?', options:['All roses fade quickly','Some roses fade quickly','No roses fade quickly','Cannot be determined'], correctIndices:[3], marks:2 },
    ]
  }
];

export const DEMO_COURSES: Course[] = [
  {
    id:'c1',
    slug:'upsc-foundation-2026-27',
    title:'UPSC Foundation Course 2026-27 (Prelims + Mains + Interview)',
    subtitle:'Complete 12-month program covering GS I-IV, Essay, CSAT, Optional guidance & interview prep. Live + Recorded.',
    category:'Foundation',
    level:'Beginner',
    instructor:'Dr. Ibemhal Devi & Team',
    instructorAvatar:'https://i.pravatar.cc/150?img=5',
    thumbnail:'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800&q=80',
    price: 24999,
    originalPrice: 49999,
    rating: 4.8,
    ratingCount: 3421,
    students: 10420,
    language:'English + Hindi',
    lastUpdated:'Aug 2026',
    tags:['UPSC','Foundation','Live','Interview'],
    isBestseller: true,
    zoomWebinarEnabled: true,
    zoomMeetingId:'87630774193',
    sections:[
      { id:'s1', title:'Orientation & Strategy', order:1, lessons:[
        { id:'l1', title:'How to start UPSC from zero - 2026 Strategy', durationMin:42, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[DEMO_PDFS[0]], order:1, isPreview:true },
        { id:'l2', title:'Prelims vs Mains - Mindset & Timetable', durationMin:38, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[DEMO_PDFS[1]], order:2 },
        { id:'l3', title:'Live: Doubt Session - Weekly', durationMin:60, zoomMeetingId:'87630774193', pdfs:[], order:3 },
      ]},
      { id:'s2', title:'Indian Polity - Full Coverage (Laxmikant)', order:2, lessons:[
        { id:'l4', title:'Historical Background & Making of Constitution', durationMin:55, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[DEMO_PDFS[3]], order:1 },
        { id:'l5', title:'Fundamental Rights & DPSP - PYQ Analysis', durationMin:48, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[], quizId:'quiz-polity-1', order:2 },
        { id:'l6', title:'Parliament - Lok Sabha & Rajya Sabha deep dive', durationMin:62, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[], order:3 },
      ]},
      { id:'s3', title:'Modern History + Current Affairs Integration', order:3, lessons:[
        { id:'l7', title:'Freedom Struggle 1857-1947 - Timeline mastery', durationMin:50, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[], order:1 },
        { id:'l8', title:'Daily News Analysis - The Hindu + PIB', durationMin:30, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[DEMO_PDFS[2]], order:2 },
      ]},
    ],
    pdfs: DEMO_PDFS,
    quizIds:['quiz-polity-1'],
  },
  {
    id:'c2',
    slug:'prelims-crash-course-2026',
    title:'Prelims Crash Course 2026 — 90 Days to Clear',
    subtitle:'High-yield revision: 5000+ MCQs, 30 mock tests, daily CA, fastest prelims focussed program.',
    category:'Prelims',
    level:'Intermediate',
    instructor:'R.K. Singh',
    instructorAvatar:'https://i.pravatar.cc/150?img=12',
    thumbnail:'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&q=80',
    price: 7999,
    originalPrice: 15999,
    rating: 4.7,
    ratingCount: 2104,
    students: 6230,
    language:'English',
    lastUpdated:'Sep 2026',
    tags:['Prelims','MCQ','Test Series'],
    isFeatured: true,
    sections:[
      { id:'s1', title:'GS Paper I - Rapid Revision', order:1, lessons:[
        { id:'l1', title:'History + Art & Culture - 100 Most Expected', durationMin:45, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[], order:1 },
        { id:'l2', title:'Geography + Environment - Maps & PYQs', durationMin:50, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[], quizId:'quiz-polity-1', order:2 },
      ]},
    ],
    pdfs: [DEMO_PDFS[1]],
    quizIds:['quiz-polity-1','quiz-csat-1'],
  },
  {
    id:'c3',
    slug:'mains-answer-writing-mastery',
    title:'Mains Answer Writing Mastery + Essay + Ethics',
    subtitle:'Daily answer writing, personalized evaluation, model answers, 70+ tests for Mains 2026.',
    category:'Mains',
    level:'Advanced',
    instructor:'Anjali Mehta IAS',
    instructorAvatar:'https://i.pravatar.cc/150?img=32',
    thumbnail:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80',
    price: 12999,
    originalPrice: 24999,
    rating: 4.9,
    ratingCount: 1892,
    students: 4120,
    language:'English + Hindi',
    lastUpdated:'Aug 2026',
    tags:['Mains','Answer Writing','Essay'],
    sections:[
      { id:'s1', title:'GS Paper II - Polity & Governance', order:1, lessons:[
        { id:'l1', title:'How to structure a 10/15 marker', durationMin:35, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[], order:1 },
      ]},
    ],
    pdfs: [],
    quizIds:[],
  },
  {
    id:'c4',
    slug:'optional-psir-anthropology',
    title:'Optional - PSIR / Anthropology / Geography (Choose One)',
    subtitle:'500 marks in Mains - detailed optional coverage with toppers notes and test series.',
    category:'Optional',
    level:'Advanced',
    instructor:'Prof. Verma',
    instructorAvatar:'https://i.pravatar.cc/150?img=15',
    thumbnail:'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80',
    price: 15999,
    originalPrice: 29999,
    rating: 4.6,
    ratingCount: 980,
    students: 2100,
    language:'English',
    lastUpdated:'Jul 2026',
    tags:['Optional','PSIR','Anthropology'],
    sections:[
      { id:'s1', title:'Paper I - Concepts', order:1, lessons:[
        { id:'l1', title:'Political Theory - Thinkers', durationMin:60, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[], order:1 },
      ]},
    ],
    pdfs: [],
    quizIds:[],
  },
  {
    id:'c5',
    slug:'current-affairs-year-long',
    title:'Current Affairs 360° — Daily, Monthly, Yearly + PDFs',
    subtitle:'The Hindu, Indian Express, PIB, Yojana, Kurukshetra — daily 30-min analysis + monthly PDF compilation.',
    category:'Current Affairs',
    level:'Beginner',
    instructor:'Ibemhal CA Team',
    instructorAvatar:'https://i.pravatar.cc/150?img=26',
    thumbnail:'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    price: 3999,
    originalPrice: 7999,
    rating: 4.8,
    ratingCount: 4200,
    students: 15400,
    language:'English + Hindi',
    lastUpdated:'Sep 2026',
    tags:['Current Affairs','Daily','PDF'],
    isFeatured: true,
    sections:[
      { id:'s1', title:'September 2026', order:1, lessons:[
        { id:'l1', title:'02 Sep - Daily News Analysis', durationMin:28, videoUrl:'https://www.youtube.com/embed/dQw4w9WgXcQ', pdfs:[DEMO_PDFS[2]], order:1 },
      ]},
    ],
    pdfs: [DEMO_PDFS[2]],
    quizIds:[],
  },
  {
    id:'c6',
    slug:'test-series-prelims-mains-combo',
    title:'All India Test Series — Prelims (30) + Mains (25)',
    subtitle:'UPSC-level simulation, All India Ranking, detailed evaluation & analytics dashboard.',
    category:'Test Series',
    level:'Intermediate',
    instructor:'Abhyas Evaluation Cell',
    instructorAvatar:'https://i.pravatar.cc/150?img=8',
    thumbnail:'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80',
    price: 5999,
    originalPrice: 11999,
    rating: 4.7,
    ratingCount: 3100,
    students: 8900,
    language:'English',
    lastUpdated:'Sep 2026',
    tags:['Test Series','Prelims','Mains'],
    sections:[
      { id:'s1', title:'Prelims Tests', order:1, lessons:[
        { id:'l1', title:'Test 01 - GS Full Syllabus', durationMin:120, pdfs:[], quizId:'quiz-polity-1', order:1 },
      ]},
    ],
    pdfs: [],
    quizIds:['quiz-polity-1','quiz-csat-1'],
  },
];

export const PACKAGES: Package[] = [
  {
    id:'pkg-foundation',
    name:'Foundation Pro',
    subtitle:'Prelims + Mains + Interview — 12 Months',
    price: 24999,
    originalPrice: 49999,
    durationMonths: 12,
    badge:'BESTSELLER',
    popular: true,
    color:'#4f46e5',
    courseIds:['c1','c3','c5','c6'],
    features:['All GS Papers + CSAT','Daily Live Classes via Zoom','PDF Notes + Mains Evaluation','30 Prelims + 25 Mains Tests','Interview Guidance','1:1 Mentorship Slot Booking'],
  },
  {
    id:'pkg-prelims',
    name:'Prelims Focus',
    subtitle:'90-Day Crash + Test Series',
    price: 9999,
    originalPrice: 19999,
    durationMonths: 4,
    color:'#0f766e',
    courseIds:['c2','c5','c6'],
    features:['GS + CSAT Crash','5000+ MCQs','30 Mock Tests + AIR','Daily CA PDFs','PYQ Solved Vault'],
  },
  {
    id:'pkg-mains',
    name:'Mains Mastery',
    subtitle:'Answer Writing + Essay + Ethics',
    price: 14999,
    originalPrice: 29999,
    durationMonths: 6,
    badge:'NEW',
    color:'#be185d',
    courseIds:['c3','c4','c6'],
    features:['70+ Mains Tests','Personal Copy Checking','Optional Guidance','Essay Masterclasses','Live Evaluation Sessions (Zoom)'],
  },
  {
    id:'pkg-optional',
    name:'Optional Edge',
    subtitle:'PSIR / Anthro / Geography — 500 Marks',
    price: 15999,
    originalPrice: 29999,
    durationMonths: 8,
    color:'#7c3aed',
    courseIds:['c4'],
    features:['Paper I + II Full Coverage','Topper Notes PDFs','Weekly Mini Tests','Zoom Doubt Marathons'],
  },
  {
    id:'pkg-ca',
    name:'CA 360°',
    subtitle:'Daily CA + Monthly PDFs — 12 Months',
    price: 3999,
    originalPrice: 7999,
    durationMonths: 12,
    color:'#ea580c',
    courseIds:['c5'],
    features:['Daily 30-min Analysis','Monthly PDF Compilation','Prelims CA Quiz Bank','The Hindu + PIB Summary'],
  },
];

export const DEMO_LIVE: LiveClass[] = [
  { id:'live1', title:'Polity - Article 32 & Judicial Review (Live)', courseId:'c1', instructor:'Dr. Ibemhal Devi', meetingId:'87630774193', passcode:'IAS2026', startAt: Date.now() + 1000*60*60*2, durationMin:90, status:'scheduled' },
  { id:'live2', title:'Daily News Analysis - 02 Sep', courseId:'c5', instructor:'CA Team', meetingId:'87630774194', startAt: Date.now() - 1000*60*20, durationMin:45, status:'live' },
  { id:'live3', title:'Mains Answer Writing - Live Evaluation', courseId:'c3', instructor:'Anjali Mehta', meetingId:'87630774195', startAt: Date.now() + 1000*60*60*24, durationMin:60, status:'scheduled' },
];

export const EXAM_PATTERN = {
  prelims: [
    { paper:'GS Paper I', marks:200, duration:'2 hrs', type:'Objective • 100 Qs', note:'Cut-off deciding • Merit' },
    { paper:'CSAT Paper II', marks:200, duration:'2 hrs', type:'Objective • 80 Qs', note:'Qualifying - 33% (66/200)' },
  ],
  mains: [
    { paper:'Essay', marks:250 },
    { paper:'GS I - History, Heritage, Geo', marks:250 },
    { paper:'GS II - Polity, Governance, IR', marks:250 },
    { paper:'GS III - Economy, S&T, Environment, Security', marks:250 },
    { paper:'GS IV - Ethics, Integrity, Aptitude', marks:250 },
    { paper:'Optional Paper I', marks:250 },
    { paper:'Optional Paper II', marks:250 },
  ],
  interview: 275,
  totalMerit: 2025,
};
