'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { useLmsStore } from '@/lib/lms/store';
import CourseCard from '@/components/lms/CourseCard';
import StudyCalendar from '@/components/lms/Calendar';
import { PdfCard } from '@/components/lms/PdfViewer';
import PdfViewer from '@/components/lms/PdfViewer';
import QuizRunner from '@/components/lms/QuizRunner';
import { BookOpen, Video, FileText, Award, Clock, Flame, Target, CheckCircle2, Play, BarChart3 } from 'lucide-react';
export default function LearnPage(){
  const currentUser = useLmsStore(s=>s.currentUser);
  const courses = useLmsStore(s=>s.courses);
  const quizzes = useLmsStore(s=>s.quizzes);
  const enrollments = useLmsStore(s=>s.enrollments);
  const studyLogs = useLmsStore(s=>s.studyLogs);
  const [activePdf, setActivePdf] = useState<any>(null);
  const [activeQuiz, setActiveQuiz] = useState<any>(null);
  const myEnrollments = useMemo(()=> currentUser ? enrollments.filter(e=>e.userId===currentUser.id) : [], [enrollments, currentUser]);
  const myCourses = useMemo(()=> courses.filter(c=> myEnrollments.some(e=>e.courseId===c.id)), [courses, myEnrollments]);
  const continueCourse = myCourses[0];
  const totalMinutes = studyLogs.reduce((a,b)=>a+b.minutes,0);
  const completedLessons = myEnrollments.reduce((a,e)=>a+e.completedLessonIds.length,0);
  const avgProgress = myEnrollments.length ? Math.round(myEnrollments.reduce((a,e)=>a+e.progress,0)/myEnrollments.length) : 0;
  if(!currentUser){
    return (<div className="max-w-[1400px] mx-auto px-4 py-16 text-center"><div className="bg-white border border-neutral-200 rounded-[24px] p-8 max-w-lg mx-auto"><div className="w-14 h-14 rounded-2xl bg-[#0f172a] text-white flex items-center justify-center mx-auto"><BookOpen className="w-7 h-7"/></div><h2 className="font-black text-xl mt-4">Sign in to track your studies</h2><p className="text-sm text-neutral-500 mt-2">Your Student ID unlocks live classes, PDFs, replays & calendar.</p><Link href="/lms" className="mt-4 inline-flex bg-[#0f172a] text-white px-6 py-2.5 rounded-full text-sm font-black">Go to Explore</Link></div></div>);
  }
  return (
    <div className="max-w-[1400px] mx-auto px-3 sm:px-6 py-6 sm:py-8">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div><h1 className="text-[24px] sm:text-[28px] font-black tracking-tighter">My Learning</h1><p className="text-sm text-neutral-500">Welcome back, <span className="font-bold text-neutral-900">{currentUser.name}</span> • Student ID: {currentUser.id.slice(0,8).toUpperCase()} • {currentUser.email}</p></div>
        <div className="flex gap-2"><Link href="/lms" className="bg-white border border-neutral-200 px-4 py-2 rounded-full text-sm font-bold hover:bg-neutral-50">Browse courses</Link><Link href="/lms/live/live1" className="bg-[#0f172a] text-white px-4 py-2 rounded-full text-sm font-black">Join Live →</Link></div>
      </div>
      <div className="mt-6 grid grid-cols-2 lg:grid-cols-4 gap-3">
        <div className="bg-white border border-neutral-200 rounded-[20px] p-4 flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-[#eef2ff] flex items-center justify-center"><Target className="w-5 h-5 text-[#4338ca]"/></div><div><div className="text-[11px] font-bold text-neutral-500">AVG PROGRESS</div><div className="text-[20px] font-black leading-none">{avgProgress}%</div></div></div>
        <div className="bg-white border border-neutral-200 rounded-[20px] p-4 flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-[#fff7ed] flex items-center justify-center"><Clock className="w-5 h-5 text-[#ea580c]"/></div><div><div className="text-[11px] font-bold text-neutral-500">TIME STUDIED</div><div className="text-[20px] font-black leading-none">{Math.round(totalMinutes/60*10)/10}h</div></div></div>
        <div className="bg-white border border-neutral-200 rounded-[20px] p-4 flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-emerald-50 flex items-center justify-center"><CheckCircle2 className="w-5 h-5 text-emerald-600"/></div><div><div className="text-[11px] font-bold text-neutral-500">LESSONS DONE</div><div className="text-[20px] font-black leading-none">{completedLessons}</div></div></div>
        <div className="bg-gradient-to-br from-[#0f172a] to-[#1e1b4b] text-white rounded-[20px] p-4 flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-white/15 flex items-center justify-center"><Flame className="w-5 h-5 text-[#f59e0b]"/></div><div><div className="text-[11px] font-bold opacity-70">STREAK</div><div className="text-[20px] font-black leading-none">6 days 🔥</div></div></div>
      </div>
      <div className="mt-6 grid lg:grid-cols-[1.35fr_0.75fr] gap-6 items-start">
        <div className="space-y-6">
          {continueCourse && (<div className="bg-white border border-neutral-200 rounded-[20px] overflow-hidden"><div className="px-4 sm:px-5 py-4 flex items-center justify-between border-b border-neutral-100"><h3 className="font-black flex items-center gap-2"><Play className="w-4 h-4"/> Continue watching</h3><Link href={`/lms/course/${continueCourse.id}`} className="text-xs font-black bg-[#0f172a] text-white px-3 py-1.5 rounded-full">Resume →</Link></div><div className="p-4 sm:p-5 grid sm:grid-cols-[280px_1fr] gap-4"><div className="relative aspect-video rounded-xl overflow-hidden bg-neutral-900"><img src={continueCourse.thumbnail} alt={continueCourse.title} className="w-full h-full object-cover"/><div className="absolute inset-0 bg-black/20"/><div className="absolute bottom-2 left-2 right-2 h-1.5 bg-white/30 rounded-full overflow-hidden"><div className="h-full bg-[#f59e0b]" style={{width: `${myEnrollments.find(e=>e.courseId===continueCourse.id)?.progress||0}%`}}/></div></div><div><div className="text-xs font-black tracking-wide text-[#4338ca]">{continueCourse.category}</div><h4 className="font-bold leading-tight mt-1">{continueCourse.title}</h4><p className="text-xs text-neutral-500 mt-1 line-clamp-2">{continueCourse.subtitle}</p><div className="mt-3 flex flex-wrap gap-2">{continueCourse.sections[0]?.lessons.slice(0,3).map(l=>(<Link key={l.id} href={`/lms/course/${continueCourse.id}`} className="text-xs bg-neutral-50 border border-neutral-200 px-2.5 py-1.5 rounded-full hover:bg-neutral-100 flex items-center gap-1.5"><Video className="w-3 h-3"/> {l.title.slice(0,28)}...</Link>))}</div></div></div></div>)}
          <div><h3 className="font-black flex items-center gap-2"><BookOpen className="w-4 h-4"/> My courses • {myCourses.length}</h3>{myCourses.length===0 ? (<div className="mt-3 bg-white border border-dashed border-neutral-300 rounded-[20px] p-8 text-center"><div className="text-sm font-bold">No enrollments yet</div><div className="text-xs text-neutral-500 mt-1">Enroll from packages or Explore — your progress will appear here with calendar tracking.</div><Link href="/lms#packages" className="mt-3 inline-flex bg-[#0f172a] text-white px-5 py-2 rounded-full text-sm font-black">View packages</Link></div>) : (<div className="mt-3 grid sm:grid-cols-2 gap-4">{myCourses.map(c=>{const prog = myEnrollments.find(e=>e.courseId===c.id)?.progress||0; return <CourseCard key={c.id} course={c} enrolled progress={prog} />;})}</div>)}</div>
          <div className="bg-white border border-neutral-200 rounded-[20px] p-4 sm:p-5"><h3 className="font-black flex items-center gap-2"><FileText className="w-4 h-4"/> PDF materials • Library</h3><p className="text-xs text-neutral-500 mt-1">All PDFs from your enrolled courses + free resources. View inline or download.</p><div className="mt-4 grid gap-3">{myCourses.flatMap(c=>c.pdfs).slice(0,6).map(pdf=>(<PdfCard key={pdf.id} pdf={pdf} onOpen={()=>setActivePdf(pdf)} />))}{myCourses.flatMap(c=>c.pdfs).length===0 && <div className="text-sm text-neutral-500 bg-neutral-50 border border-neutral-200 rounded-xl p-4 text-center">No PDFs yet — admin will upload.</div>}</div>{activePdf && (<div className="mt-4"><PdfViewer pdf={activePdf} onClose={()=>setActivePdf(null)} /></div>)}</div>
          <div className="bg-white border border-neutral-200 rounded-[20px] p-4 sm:p-5"><h3 className="font-black flex items-center gap-2"><Award className="w-4 h-4"/> Quizzes & Mock tests</h3><div className="mt-4 grid gap-3">{quizzes.map(q=>(<div key={q.id} className="border border-neutral-200 rounded-2xl p-4 flex flex-wrap items-center justify-between gap-3 hover:shadow-md transition"><div><div className="text-sm font-bold">{q.title}</div><div className="text-xs text-neutral-500">{q.description} • {q.questions.length} Qs • {q.durationMin} min • {q.totalMarks} marks</div></div><button onClick={()=>setActiveQuiz(q)} className="bg-[#0f172a] text-white px-4 py-2 rounded-full text-xs font-black hover:bg-black">Start quiz</button></div>))}</div>{activeQuiz && (<div className="mt-4"><QuizRunner quiz={activeQuiz} onClose={()=>setActiveQuiz(null)} /></div>)}</div>
        </div>
        <div className="space-y-6 lg:sticky lg:top-[88px]">
          <StudyCalendar />
          <div className="bg-white border border-neutral-200 rounded-[20px] p-4 sm:p-5"><h3 className="font-black flex items-center gap-2 text-sm"><BarChart3 className="w-4 h-4"/> Track your progress</h3><div className="mt-4 space-y-3">{myEnrollments.map(en=>{const course = courses.find(c=>c.id===en.courseId); if(!course) return null; return (<div key={en.courseId} className="border border-neutral-100 rounded-2xl p-3 bg-[#f8fafc]"><div className="flex gap-3"><img src={course.thumbnail} alt={course.title} className="w-12 h-12 rounded-xl object-cover"/><div className="flex-1 min-w-0"><div className="text-xs font-bold leading-tight line-clamp-1">{course.title}</div><div className="text-[11px] text-neutral-500">{en.completedLessonIds.length} / {course.sections.reduce((a,s)=>a+s.lessons.length,0)} lessons</div><div className="mt-2 h-2 bg-neutral-200 rounded-full overflow-hidden"><div className="h-full bg-[#4338ca]" style={{width: `${en.progress}%`}}/></div></div><div className="text-right"><div className="text-sm font-black">{en.progress}%</div><Link href={`/lms/course/${course.id}`} className="text-[11px] font-black text-[#4338ca] hover:underline">Open</Link></div></div></div>);})}{myEnrollments.length===0 && <div className="text-xs text-neutral-500 text-center py-4">Enroll to see progress rings & calendar</div>}</div></div>
          <div className="bg-[#0f172a] text-white rounded-[20px] p-4 sm:p-5"><h3 className="font-black flex items-center gap-2 text-sm"><Video className="w-4 h-4 text-[#f59e0b]"/> Upcoming live (Zoom)</h3><div className="mt-3 space-y-2">{useLmsStore.getState().liveClasses.map(l=>(<Link key={l.id} href={`/lms/live/${l.id}`} className="block bg-white/10 border border-white/10 rounded-2xl p-3 hover:bg-white/15"><div className="text-xs font-black">{l.title}</div><div className="text-[11px] opacity-70">{new Date(l.startAt).toLocaleString('en-IN')} • {l.durationMin}m • {l.instructor}</div><span className={`inline-flex mt-2 text-[11px] font-black px-2 py-1 rounded-full ${l.status==='live'?'bg-emerald-500 text-white':'bg-white text-black'}`}>{l.status==='live'?'● LIVE':'Scheduled'}</span></Link>))}</div></div>
          <div className="bg-[#fff7ed] border border-[#fed7aa] rounded-[20px] p-4"><div className="text-sm font-black">Need help?</div><div className="text-xs text-[#9a3412] mt-1">Mentorship / Counselling slot booking — same Student ID for all live access, PDFs & replays.</div><Link href="/lms/live/live1" className="mt-3 inline-flex bg-[#0f172a] text-white px-4 py-2 rounded-full text-xs font-black">Book a slot</Link></div>
        </div>
      </div>
    </div>
  );
}
